service: crud-serverless-users

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - 'dynamodb:Query'
            - 'dynamodb:*'
          Resource: arn:aws:dynamodb:us-east-2:226175033599:table/usersTable

functions:
  getUser:
    handler: getUser/handler.getUser
    package:
      patterns:
        - "getuser/handler.js"
    events:
      - http:
          path: users/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true
  createUser:
    handler: createUser/handler.createUser
    package:
      patterns:
        - "createUser/handler.js"
    events:
      - http:
          path: users
          method: POST
          request:
            schemas:
              application/json: ${file(schemas/user-schema.json)}

  updateUser:
    handler: updateUser/handler.updateUser
    package:
      patterns:
        - "updateUser/handler.js"
    events:
      - http:
          path: users/{id}
          method: PATCH
          request:
            parameters:
              paths:
                id: true
            schemas:
              application/json: ${file(schemas/user-schema.json)}
  getUsers:
    handler: getUsers/handler.getUsers
    package:
      patterns:
        - "updateUsers/handler.js"
    events:
      - http:
          path: users
          method: GET

  deleteUser:
    handler: deleteUser/handler.deleteUser
    package:
      patterns:
        - "deleteUser/handler.py"
    runtime: python3.8
    events:
      - http:
          path: users/{id}
          method: DELETE
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-offline
  - serverless-dynamodb

custom:
  serverless-dynamodb:
    stages:
      - dev
    port: 8000
    docker: false
    start:
      migrate: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

package: 
  individually: true
  patterns:
    - "!.dynamodb"
    - "!node_modules"